basePath: /
definitions:
  model.ApplicantSignupAPIError0:
    properties:
      error:
        example: email cannot be empty
        type: string
    type: object
  model.ApplicantSignupAPIError1:
    properties:
      error:
        example: email already registered
        type: string
    type: object
  model.ApplicantSignupEmailStruct:
    properties:
      Email:
        example: wang374@uiuc.edu
        type: string
    type: object
  model.ApplicantSignupSuccessStruct:
    properties:
      message:
        example: verification email sent
        type: string
    type: object
  model.ReferrerSignupAPIError0:
    properties:
      error:
        example: email cannot be empty
        type: string
    type: object
  model.ReferrerSignupAPIError1:
    properties:
      error:
        example: email already registered
        type: string
    type: object
  model.ReferrerSignupEmailStruct:
    properties:
      Email:
        example: admin@jogchat.com
        type: string
    type: object
  model.ReferrerSignupSuccessStruct:
    properties:
      message:
        example: verification email sent
        type: string
    type: object
host: 178.128.0.108:3001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /applicant_signup:
    post:
      consumes:
      - application/json
      description: ApplicantSignup
      parameters:
      - description: Body JSON
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ApplicantSignupEmailStruct'
          type: object
      responses:
        "200":
          description: 'Success: verification email sent'
          schema:
            $ref: '#/definitions/model.ApplicantSignupSuccessStruct'
            type: object
        "400":
          description: email already registered
          schema:
            $ref: '#/definitions/model.ApplicantSignupAPIError1'
            type: object
      summary: ApplicantSignup
  /referrer_signup:
    post:
      consumes:
      - application/json
      description: ReferrerSignup
      parameters:
      - description: Body JSON
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ReferrerSignupEmailStruct'
          type: object
      responses:
        "200":
          description: 'Success: verification email sent'
          schema:
            $ref: '#/definitions/model.ReferrerSignupSuccessStruct'
            type: object
        "400":
          description: email already registered
          schema:
            $ref: '#/definitions/model.ReferrerSignupAPIError1'
            type: object
      summary: ReferrerSignup
swagger: "2.0"
