basePath: /
definitions:
  model.ActivateAndSignupRequest:
    properties:
      Email:
        example: wang374@uiuc.edu
        type: string
      Password:
        example: wang374password
        type: string
      Token:
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzEyOTE4MTgsImlzcyI6ImpvZ2NoYXQuY29tIiwic3ViIjoic3VwZXJjaGFvcmFuQGdtYWlsLmNvbSJ9.yYQOAIyHQJJUntMGtRaAm2bXF-HvvsK6vHjhe0SDsHg
        type: string
      Username:
        example: wang374
        type: string
    type: object
  model.ActivateAndSignupResponseAPIError0:
    properties:
      error:
        example: username already in use
        type: string
    type: object
  model.ActivateAndSignupResponseAPIError1:
    properties:
      error:
        example: invalid token
        type: string
    type: object
  model.ActivateAndSignupResponseAPIError2:
    properties:
      error:
        example: email already activated
        type: string
    type: object
  model.ActivateAndSignupResponseSuccess:
    properties:
      AuthToken:
        type: string
      Email:
        example: wang374@uiuc.edu
        type: string
      UserId:
        type: string
      Username:
        example: wang374
        type: string
    type: object
  model.ApplicantSignupEmailRequest:
    properties:
      Email:
        example: wang374@uiuc.edu
        type: string
    type: object
  model.ApplicantSignupResponseAPIError0:
    properties:
      error:
        example: email cannot be empty
        type: string
    type: object
  model.ApplicantSignupResponseAPIError1:
    properties:
      error:
        example: email already registered
        type: string
    type: object
  model.ApplicantSignupResponseSuccess:
    properties:
      message:
        example: verification email sent
        type: string
    type: object
  model.ReferrerSignupEmailRequest:
    properties:
      Email:
        example: admin@jogchat.com
        type: string
    type: object
  model.ReferrerSignupResponseAPIError0:
    properties:
      error:
        example: email cannot be empty
        type: string
    type: object
  model.ReferrerSignupResponseAPIError1:
    properties:
      error:
        example: email already registered
        type: string
    type: object
  model.ReferrerSignupResponseSuccess:
    properties:
      message:
        example: verification email sent
        type: string
    type: object
host: 178.128.0.108:3001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /activate_and_signup:
    post:
      consumes:
      - application/json
      description: When user click on the GET link in user email, it will hit a frontend
        page as a GET request with
      parameters:
      - description: ActivateAndSignupRequest is a POST JSON type
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ActivateAndSignupRequest'
          type: object
      responses:
        "200":
          description: 'Success: verification email sent'
          schema:
            $ref: '#/definitions/model.ActivateAndSignupResponseSuccess'
            type: object
        "400":
          description: email already activated
          schema:
            $ref: '#/definitions/model.ActivateAndSignupResponseAPIError2'
            type: object
      summary: ActivateAndSignup
  /applicant_check_signup_email:
    post:
      consumes:
      - application/json
      description: Provide a school/university edu email to sign up for the applicant
        portal, if the email does not
      parameters:
      - description: ApplicantSignupEmailRequest is a POST JSON type
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ApplicantSignupEmailRequest'
          type: object
      responses:
        "200":
          description: 'Success: verification email sent'
          schema:
            $ref: '#/definitions/model.ApplicantSignupResponseSuccess'
            type: object
        "400":
          description: email already registered
          schema:
            $ref: '#/definitions/model.ApplicantSignupResponseAPIError1'
            type: object
      summary: ApplicantCheckSignupEmail
  /referrer_check_signup_email:
    post:
      consumes:
      - application/json
      description: Onboarding user will provide a company email to sign up for the
        referral portal, if the email does not
      parameters:
      - description: ReferrerSignupEmailRequest is a POST JSON type
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.ReferrerSignupEmailRequest'
          type: object
      responses:
        "200":
          description: 'Success: verification email sent'
          schema:
            $ref: '#/definitions/model.ReferrerSignupResponseSuccess'
            type: object
        "400":
          description: email already registered
          schema:
            $ref: '#/definitions/model.ReferrerSignupResponseAPIError1'
            type: object
      summary: ReferrerCheckSignupEmail
swagger: "2.0"
