// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-07-08 16:51:38.045458787 -0700 PDT m=+0.027674667

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "This is a ReferHelper API server.",
        "title": "ReferHelper API",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "admin@jogchat.com",
            "email": "admin@jogchat.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0"
    },
    "host": "178.128.0.108:3001",
    "basePath": "/",
    "paths": {
        "/activate_and_signup": {
            "post": {
                "description": "When user click on the GET link in user email, it will hit a frontend page as a GET request with {Email, Token} as parameters. The frontend page should then provide user with a form that ask for (Email(prefilled), Username, password, token(prefilled and hidden)). Once frontend gather all infos from the user, frontend should POST call this [ActivateAndSignup endpoint] with a post request that has {email, username, password, token} as JSON to sign the user up. This endpoint will both signup the user and activate their account.",
                "consumes": [
                    "application/json"
                ],
                "summary": "ActivateAndSignup",
                "parameters": [
                    {
                        "description": "ActivateAndSignupRequest is a POST JSON type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ActivateAndSignupRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success: verification email sent",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ActivateAndSignupResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "email already activated",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ActivateAndSignupResponseAPIError2"
                        }
                    }
                }
            }
        },
        "/applicant_check_signup_email": {
            "post": {
                "description": "Provide a school/university edu email to sign up for the applicant portal, if the email does not exists in schemaless database, we will send the email an activation link",
                "consumes": [
                    "application/json"
                ],
                "summary": "ApplicantCheckSignupEmail",
                "parameters": [
                    {
                        "description": "ApplicantSignupEmailRequest is a POST JSON type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApplicantSignupEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success: verification email sent",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApplicantSignupResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "email already registered",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ApplicantSignupResponseAPIError1"
                        }
                    }
                }
            }
        },
        "/referrer_check_signup_email": {
            "post": {
                "description": "Onboarding user will provide a company email to sign up for the referral portal, if the email does not exists in schemaless database, we will send the email an activation link",
                "consumes": [
                    "application/json"
                ],
                "summary": "ReferrerCheckSignupEmail",
                "parameters": [
                    {
                        "description": "ReferrerSignupEmailRequest is a POST JSON type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ReferrerSignupEmailRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success: verification email sent",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ReferrerSignupResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "email already registered",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.ReferrerSignupResponseAPIError1"
                        }
                    }
                }
            }
        },
        "/signin": {
            "post": {
                "description": "After user click on sign-in button, front-end will call this endpoint with a JSON wrapped {Email and Password}, the end point will then return an AuthToken on success. Front-end should store the authtoken for user either in session or cookie for user. To access password protect resource later, front-end needs to pass (username+AuthToken) to backend to verify user identity. This is called JWT Auth flow.",
                "consumes": [
                    "application/json"
                ],
                "summary": "Signin",
                "parameters": [
                    {
                        "description": "SigninRequest is a POST JSON type",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SigninRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success: sign in request succeed",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SigninResponseSuccess"
                        }
                    },
                    "400": {
                        "description": "invalid password",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/model.SigninResponseAPIError2"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ActivateAndSignupRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "wang374@uiuc.edu"
                },
                "Password": {
                    "type": "string",
                    "example": "wang374password"
                },
                "Token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MzEyOTE4MTgsImlzcyI6ImpvZ2NoYXQuY29tIiwic3ViIjoic3VwZXJjaGFvcmFuQGdtYWlsLmNvbSJ9.yYQOAIyHQJJUntMGtRaAm2bXF-HvvsK6vHjhe0SDsHg"
                },
                "Username": {
                    "type": "string",
                    "example": "wang374"
                }
            }
        },
        "model.ActivateAndSignupResponseAPIError0": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "username already in use"
                }
            }
        },
        "model.ActivateAndSignupResponseAPIError1": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid token"
                }
            }
        },
        "model.ActivateAndSignupResponseAPIError2": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email already activated"
                }
            }
        },
        "model.ActivateAndSignupResponseSuccess": {
            "type": "object",
            "properties": {
                "AuthToken": {
                    "type": "string"
                },
                "Email": {
                    "type": "string",
                    "example": "wang374@uiuc.edu"
                },
                "UserId": {
                    "type": "string"
                },
                "Username": {
                    "type": "string",
                    "example": "wang374"
                }
            }
        },
        "model.ApplicantSignupEmailRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "wang374@uiuc.edu"
                }
            }
        },
        "model.ApplicantSignupResponseAPIError0": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email cannot be empty"
                }
            }
        },
        "model.ApplicantSignupResponseAPIError1": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email already registered"
                }
            }
        },
        "model.ApplicantSignupResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "verification email sent"
                }
            }
        },
        "model.ReferrerSignupEmailRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "admin@jogchat.com"
                }
            }
        },
        "model.ReferrerSignupResponseAPIError0": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email cannot be empty"
                }
            }
        },
        "model.ReferrerSignupResponseAPIError1": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email already registered"
                }
            }
        },
        "model.ReferrerSignupResponseSuccess": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "verification email sent"
                }
            }
        },
        "model.SigninRequest": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "wang374@uiuc.edu"
                },
                "Password": {
                    "type": "string",
                    "example": "wang374password"
                }
            }
        },
        "model.SigninResponseAPIError0": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "email not registered"
                }
            }
        },
        "model.SigninResponseAPIError1": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "please verify your email"
                }
            }
        },
        "model.SigninResponseAPIError2": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "invalid password"
                }
            }
        },
        "model.SigninResponseSuccess": {
            "type": "object",
            "properties": {
                "Email": {
                    "type": "string",
                    "example": "wang374@uiuc.edu"
                },
                "Password": {
                    "type": "string",
                    "example": "wang374password"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
